// Builds supabase/seed.sql from free-exercise-db (public domain, https://github.com/yuhonas/free-exercise-db).
// Run from beginner-fit/:  node scripts/build-exercise-seed.ts
import { writeFileSync } from 'node:fs';
import { stressAreas } from '../src/utils/stress-tags.ts';

const SOURCE = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/dist/exercises.json';

type Raw = {
  id: string;
  name: string;
  level: string;
  category: string;
  equipment: string | null;
  force: string | null;
  mechanic: string | null;
  primaryMuscles: string[];
  secondaryMuscles: string[];
  instructions: string[];
  images: string[];
};

const text = (v: string | null) => (v === null ? 'null' : `'${v.replaceAll("'", "''")}'`);
const arr = (xs: string[]) => (xs.length ? `array[${xs.map(text).join(',')}]` : `'{}'`) + '::text[]';

const all: Raw[] = await (await fetch(SOURCE)).json();
// ponytail: strength moves only for the MVP; stretching/cardio categories come later.
const rows = all.filter((e) => e.level === 'beginner' && e.category === 'strength');

const values = rows.map(
  (e) =>
    `(${text(e.id)},${text(e.name)},${text(e.level)},${text(e.category)},${text(e.equipment)},${text(e.force)},${text(e.mechanic)},` +
    `${arr(e.primaryMuscles)},${arr(e.secondaryMuscles)},${arr(e.instructions)},${arr(e.images)},${arr(stressAreas(e))})`,
);

const sql = `-- Generated by scripts/build-exercise-seed.ts from free-exercise-db (public domain). ${rows.length} beginner strength exercises.
-- stress_areas are a keyword first pass (stress_reviewed = false) until a trainer reviews them.
-- Re-running never overwrites existing rows, so reviewed tags are kept.
insert into public.exercises (id, name, level, category, equipment, force, mechanic, primary_muscles, secondary_muscles, instructions, images, stress_areas)
values
${values.join(',\n')}
on conflict (id) do nothing;
`;

writeFileSync(new URL('../supabase/seed.sql', import.meta.url), sql);
console.log(`Wrote supabase/seed.sql with ${rows.length} exercises`);
